// import './components/modal.js';
import './components/accordion.js';
import './components/select-dropdown.js';
import './components/filter.js';
import './components/resize-form.js';
import './components/input-slider.js';
import './components/tab-bar.js';
import './components/keen-slider.js';
import './components/bottom-sheet.js';
// import './components/cupertino-pane.js';
console.log('components');