// import './components/modal.js';
import './components/accordion.js';
import './components/select-dropdown.js';
import './components/filter.js';
import './components/resize-form.js';
import './components/input-slider.js';
import './components/tab-bar.js';
import './components/bottom-sheet.js';
import './components/preview-calculator.js';
import './components/map-preview-animation.js';
import './components/draggable-map.js';
import './components/select-item-map.js';
import './components/select-infrastructure-map.js';
import './components/sidebar-map.js';
import './components/swiffy-slider.js';
import './components/custom-alert.js';
import './components/tree-steps-preview.js';